[project]
name = "imaginary-bifurcations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numba>=0.61.2",
    "taichi>=1.7.3",
]
